//! Generated gRPC code from `proto/`.
//!
//! This crate is the single source of truth for the server (server)
//! API surface. It generates tonic/prost Rust bindings from the `.proto`
//! files in the workspace `proto/` directory.
//!
//! Regenerated by `cargo build` via `build.rs`. The `proto/` directory at
//! the workspace root is the input.
//!
//! ## Modules
//!
//! - `common::v1` — shared types (errors, paging, identities) used across
//!   all platform services.
//! - `auth::v1` — auth service API (used by `auth-core` for token
//!   introspection).
//! - `server::v1` — server server API (orchestration, registry,
//!   admin).
//! - `release::v1` — release service API (referenced by server).
//! - `workflow::v1` — workflow service API (referenced by server).
//! - `secrets::v1` — secrets service API (referenced by server).
//! - `nodes::v1` — nodes service API (referenced by server).

pub mod common {
    pub mod v1 {
        tonic::include_proto!("platform.common.v1");

        // Re-export well-known types used across services.
        pub use prost_types::Timestamp;
    }
}

pub mod auth {
    pub mod v1 {
        tonic::include_proto!("platform.auth.v1");
    }
}

pub mod server {
    pub mod v1 {
        tonic::include_proto!("platform.server.v1");
    }
}

pub mod release {
    pub mod v1 {
        tonic::include_proto!("platform.release.v1");
    }
}

pub mod workflow {
    pub mod v1 {
        tonic::include_proto!("platform.workflow.v1");
    }
}

pub mod nodes {
    pub mod v1 {
        tonic::include_proto!("platform.nodes.v1");
    }
}

pub mod secrets {
    pub mod v1 {
        tonic::include_proto!("platform.secrets.v1");
    }
}
