//! Generated gRPC code from `proto/`.
//!
//! This crate is the single source of truth for the auth service API surface.
//! It generates tonic/prost Rust bindings from the `.proto` files in the
//! workspace `proto/` directory.
//!
//! Regenerated by `cargo build` via `build.rs`. The `proto/` directory at
//! the workspace root is the input.
//!
//! ## Modules
//!
//! - `common::v1` — shared types (errors, paging, identities) used across
//!   all platform services.
//! - `auth::v1` — auth service API (users, roles, policies, MFA, OAuth,
//!   SSO, passkeys, etc.).

pub mod common {
    pub mod v1 {
        tonic::include_proto!("platform.common.v1");

        // Re-export well-known types used across services.
        pub use prost_types::Timestamp;
    }
}

pub mod auth {
    pub mod v1 {
        tonic::include_proto!("platform.auth.v1");
    }
}
